export const TERMS_VERSION = "2026-09-06-r3";

export default function TermsContent() {
  return (
    <div className="prose prose-sm max-w-none text-gray-700">
      <p className="text-sm text-gray-500">Last updated: September 6, 2026</p>

      <p>
        These Terms and Conditions ("Terms") govern use of OrbitWorks
        ("OrbitWorks," "we," "us," or "our"), a workforce time-tracking
        platform, by businesses ("Customer," "you") and their authorized
        users, including administrators, supervisors, and workers
        ("Employees"). By creating an account or using the Service, you
        agree to these Terms.
      </p>

      <h2>1. Authority to Bind</h2>
      <p>
        If you create an account on behalf of a company or other
        organization, you represent and warrant that you have authority to
        bind that organization to these Terms. In that case, "Customer"
        refers to that organization.
      </p>

      <h2>2. The Service</h2>
      <p>
        OrbitWorks provides web and mobile tools for workforce scheduling,
        time tracking, job-site management, reporting, timesheet review,
        and optional face-verification clock-in.
      </p>
      <p>
        Customer is solely responsible for how it configures and uses the
        Service, including pay rates, schedules, overtime settings, break
        settings, job-site assignments, alerts, and other workforce rules.
      </p>
      <p>
        OrbitWorks does not provide legal, tax, payroll, accounting, or
        human resources advice. Time, overtime, pay, and other
        calculations generated by the Service are provided for Customer's
        review and do not replace Customer's payroll, wage-and-hour, tax,
        or recordkeeping obligations.
      </p>

      <h2>3. Employee Photos and Records</h2>
      <p>
        Customer may upload or enter Employee information, including
        names, job titles, phone numbers, dates of birth, hourly rates,
        assigned job sites, profile photos, and other workforce-related
        records.
      </p>
      <p>
        This information may be stored within OrbitWorks' cloud
        infrastructure for the purpose of providing the Service.
      </p>
      <p>
        Customer is responsible for ensuring that it has the legal
        authority, permissions, notices, and consents required to provide
        Employee information to OrbitWorks.
      </p>
      <p>
        Employee information may remain stored until Customer deletes the
        applicable Employee record or information, or until the Customer
        account is terminated and the applicable retention period
        described in our Privacy Policy has expired.
      </p>

      <h2>4. Biometric Data and Face Verification</h2>
      <p>
        If Customer enables face-verification features, facial images may
        be processed through a third-party facial recognition service,
        currently Amazon Web Services Rekognition.
      </p>
      <p>
        During enrollment, a facial image may be analyzed and a facial
        representation may be stored within a recognition collection
        associated with Customer's account. That representation may be
        referenced by an identifier such as a FaceId.
      </p>
      <p>
        During clock-in, clock-out, or another verification event, a
        newly captured facial image may be compared against the enrolled
        facial representation to determine whether a match is detected.
      </p>
      <p>
        Additional information about biometric collection, use,
        retention, and deletion is described in our Biometric Data Policy,
        which is incorporated into these Terms.
      </p>
      <p>
        Customer is responsible for providing all notices and obtaining
        all consents required of Customer under applicable law before
        enrolling an Employee in face verification.
      </p>
      <p>
        OrbitWorks will process biometric information in accordance with
        the Biometric Data Policy, these Terms, and applicable law.
      </p>
      <p>
        Face-verification technology is probabilistic and may produce
        inaccurate matches, failed matches, or other errors.
      </p>
      <p>
        Customer should maintain a reasonable manual review or override
        process for disputed or unsuccessful verifications and should not
        rely solely on an automated face-verification result to make an
        adverse employment decision.
      </p>

      <h2>5. Location Information</h2>
      <p>
        If Customer enables location-based features, OrbitWorks may
        process device location information, job-site location
        information, geofence results, or related information in
        connection with clock events and workforce management.
      </p>
      <p>
        Customer is responsible for providing any notices and obtaining
        any permissions or consents required by applicable law before
        using location-based tracking or verification features.
      </p>

      <h2>6. Privacy</h2>
      <p>
        Our collection, use, retention, disclosure, and deletion of
        personal information is described in our Privacy Policy.
      </p>
      <p>
        Where Customer provides information relating to Employees or
        other individuals, Customer represents that it has the authority
        and lawful basis necessary to provide that information to
        OrbitWorks.
      </p>

      <h2>7. Customer Data and Ownership</h2>
      <p>
        Customer retains ownership of data, records, photos, documents,
        clock events, employee information, and other content submitted
        to the Service by Customer or its authorized users ("Customer
        Data").
      </p>
      <p>
        Customer grants OrbitWorks a limited right to host, process,
        transmit, store, and use Customer Data only as reasonably
        necessary to provide, maintain, secure, support, and improve the
        Service and as otherwise described in the Privacy Policy.
      </p>
      <p>
        OrbitWorks and its licensors retain all rights, title, and
        interest in and to the Service, including its software,
        applications, interfaces, designs, branding, trademarks,
        documentation, technology, and related intellectual property.
        Except for the limited right to use the Service under these
        Terms, no ownership rights in OrbitWorks technology are
        transferred to Customer.
      </p>

      <h2>8. Payments and Subscriptions</h2>
      <p>
        Subscription fees are processed through our payment processor,
        currently Stripe. OrbitWorks does not receive or store full
        payment card details.
      </p>
      <p>Subscriptions automatically renew until canceled.</p>
      <p>
        Customer may cancel a subscription through the Service's billing
        settings. Unless otherwise stated, cancellation takes effect at
        the end of the current billing period, and Customer may continue
        using paid features until the end of that period.
      </p>
      <p>
        Upgrades and downgrades may result in prorated charges, credits,
        or other adjustments as displayed at the time of the change.
      </p>
      <p>
        If payment fails or remains unpaid, OrbitWorks may restrict or
        suspend access to paid features until payment is successfully
        completed.
      </p>
      <p>
        Fees are non-refundable except where required by law or where
        OrbitWorks expressly states otherwise at the time of purchase.
      </p>

      <h2>9. Customer Responsibilities</h2>
      <p>Customer is responsible for:</p>
      <ul>
        <li>(a) the accuracy of information entered or uploaded into the Service;</li>
        <li>(b) obtaining all legally required notices, authorizations, and consents relating to Employee information;</li>
        <li>(c) complying with applicable labor, wage-and-hour, employment, payroll, tax, privacy, biometric, and data-protection laws;</li>
        <li>(d) reviewing time records and payroll-related information before relying on or exporting it;</li>
        <li>(e) maintaining the confidentiality and security of account credentials;</li>
        <li>(f) promptly notifying OrbitWorks of suspected unauthorized access or account compromise; and</li>
        <li>(g) ensuring that authorized users use the Service in accordance with these Terms.</li>
      </ul>

      <h2>10. Acceptable Use</h2>
      <p>Customer may not, and may not permit any other person to:</p>
      <ul>
        <li>use the Service to collect or process information about an individual without any legally required notice or consent;</li>
        <li>use biometric, location, photo, or workforce data for unlawful surveillance, discrimination, harassment, or other unlawful purposes;</li>
        <li>falsify or manipulate time records to intentionally misrepresent hours worked;</li>
        <li>access or attempt to access another Customer's account or information without authorization;</li>
        <li>interfere with or disrupt the security, integrity, availability, or operation of the Service;</li>
        <li>probe, scan, attack, or attempt to bypass security controls, authentication systems, or rate limits;</li>
        <li>reverse engineer, decompile, disassemble, or attempt to obtain the Service's source code, except where such restriction is prohibited by law;</li>
        <li>use the Service to violate the rights of another person; or</li>
        <li>use the Service in violation of applicable law.</li>
      </ul>

      <h2>11. Payroll and Timesheet Disclaimer</h2>
      <p>
        OrbitWorks records clock events and may calculate hours,
        overtime, breaks, and estimated pay based on information and
        settings configured by Customer.
      </p>
      <p>
        Customer remains solely responsible for reviewing and approving
        time records before using or exporting them for payroll or
        employment purposes.
      </p>
      <p>
        Where the Service provides a timesheet approval process, approval
        indicates that Customer has reviewed the applicable record.
      </p>
      <p>
        OrbitWorks does not independently verify whether recorded hours,
        breaks, overtime, wages, deductions, payroll calculations, or
        employment practices comply with applicable law.
      </p>
      <p>
        Customer is responsible for maintaining any employment or payroll
        records required by applicable law and should not rely solely on
        OrbitWorks' retention periods to satisfy its legal recordkeeping
        obligations.
      </p>

      <h2>12. Suspension</h2>
      <p>
        OrbitWorks may temporarily suspend or restrict access to some or
        all of the Service where reasonably necessary because of:
      </p>
      <ul>
        <li>nonpayment;</li>
        <li>suspected fraud;</li>
        <li>a security threat;</li>
        <li>unauthorized or unlawful use;</li>
        <li>a material violation of these Terms;</li>
        <li>activity that may harm the Service, another Customer, or a third party; or</li>
        <li>a legal or regulatory requirement.</li>
      </ul>
      <p>
        Where reasonably possible, OrbitWorks will attempt to provide
        notice before suspension.
      </p>

      <h2>13. Disclaimer of Warranties</h2>
      <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE."</p>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, ORBITWORKS DISCLAIMS ALL
        WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
        WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
        NON-INFRINGEMENT, ACCURACY, AVAILABILITY, SECURITY, OR
        RELIABILITY.
      </p>
      <p>
        ORBITWORKS DOES NOT WARRANT THAT THE SERVICE WILL BE
        UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE FROM DATA LOSS.
      </p>
      <p>
        FACE-VERIFICATION RESULTS, LOCATION RESULTS, AUTOMATED ALERTS,
        TIME CALCULATIONS, PAY CALCULATIONS, AND REPORTS MAY CONTAIN
        ERRORS AND SHOULD BE REVIEWED BY CUSTOMER.
      </p>

      <h2>14. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, ORBITWORKS AND ITS
        OFFICERS, EMPLOYEES, CONTRACTORS, AND SUPPLIERS WILL NOT BE LIABLE
        FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY,
        OR PUNITIVE DAMAGES, OR FOR LOSS OF PROFITS, REVENUE, DATA, WAGES,
        BUSINESS OPPORTUNITIES, OR GOODWILL ARISING FROM OR RELATING TO
        THE SERVICE OR THESE TERMS.
      </p>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, ORBITWORKS' TOTAL
        LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THE SERVICE
        OR THESE TERMS WILL NOT EXCEED THE FEES PAID BY CUSTOMER TO
        ORBITWORKS DURING THE THREE MONTHS IMMEDIATELY PRECEDING THE
        EVENT GIVING RISE TO THE CLAIM.
      </p>
      <p>
        NOTHING IN THESE TERMS EXCLUDES OR LIMITS LIABILITY THAT CANNOT
        LEGALLY BE EXCLUDED OR LIMITED.
      </p>

      <h2>15. Indemnification</h2>
      <p>
        Customer agrees to defend, indemnify, and hold harmless OrbitWorks
        and its officers, employees, contractors, and suppliers from
        claims, liabilities, damages, judgments, costs, and reasonable
        attorneys' fees arising from or relating to:
      </p>
      <ul>
        <li>Customer's failure to obtain legally required Employee notices or consents;</li>
        <li>Customer's violation of applicable labor, wage, employment, biometric, privacy, or data-protection law;</li>
        <li>Customer's misuse of Customer Data or information generated by the Service;</li>
        <li>Customer's payroll or employment decisions;</li>
        <li>Customer's violation of these Terms; or</li>
        <li>Customer's unlawful or unauthorized use of the Service.</li>
      </ul>

      <h2>16. Third-Party Services</h2>
      <p>
        The Service relies on third-party technology and infrastructure
        providers, which may include Google Firebase, Google Cloud,
        Stripe, and Amazon Web Services.
      </p>
      <p>
        These providers may process information as necessary to provide
        their services to OrbitWorks.
      </p>
      <p>
        OrbitWorks does not control third-party services and, to the
        extent permitted by law, is not responsible for interruptions or
        failures caused solely by third-party providers or circumstances
        outside OrbitWorks' reasonable control. OrbitWorks may replace or
        change third-party providers as the Service develops.
      </p>

      <h2>17. Force Majeure</h2>
      <p>
        Neither party will be liable for delay or failure to perform
        resulting from circumstances outside its reasonable control,
        including natural disasters, severe weather, acts of government,
        labor disruptions, telecommunications failures, internet
        failures, cyberattacks, power failures, or outages of cloud
        infrastructure or other third-party providers.
      </p>

      <h2>18. Termination and Data</h2>
      <p>
        Customer may terminate its account or subscription using the
        available account or billing settings or by contacting
        OrbitWorks.
      </p>
      <p>
        OrbitWorks may terminate an account for material violation of
        these Terms, unlawful use, prolonged nonpayment, security
        concerns, or where required by law.
      </p>
      <p>
        Following termination, Customer Data will be retained or deleted
        according to the retention periods described in the Privacy
        Policy and Biometric Data Policy.
      </p>
      <p>
        Customer should export any information it wishes to retain before
        applicable deletion periods expire.
      </p>

      <h2>19. Changes to These Terms</h2>
      <p>OrbitWorks may update these Terms from time to time.</p>
      <p>
        If we make material changes, we may provide notice through the
        Service, by email, or through another reasonable method.
      </p>
      <p>The updated Terms will display a revised "Last updated" date.</p>
      <p>
        Continued use of the Service after updated Terms take effect
        constitutes acceptance of the revised Terms, except where
        applicable law requires additional consent.
      </p>

      <h2>20. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the State of Louisiana,
        without regard to conflict-of-law principles, except where
        applicable mandatory law requires otherwise.
      </p>

      <h2>21. Contact</h2>
      <p>
        Questions about these Terms may be submitted using the contact
        information provided on the OrbitWorks website.
      </p>
    </div>
  );
}